version: '3'

services:
      service:
        image: mule-service:1.0
        working_dir: /app
        depends_on:
          - mongo
          - nats
        environment:
          NODE_ENV: development
        command: npm run dev
      gateway:
        image: gateway:1.0 
        working_dir: /home/app/
        depends_on: 
          - nats
        ports:
          - 3000:3000
        environment: 
          NODE_ENV: development
        command: npm start
        
      mongo:
        image: mongo
        expose:
          - 27017
      nats:
        image: nats
        expose:
          - 4222
        ports:
          - 8222:8222
        hostname: nats-server